# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd197b2d3c1699522176c48b34f96a575d9bff97b9c070efbd13d54a5c3ef12433cf982ecd69c2a4e3cc543fec6408886301ddcec32758485b0958e09d3a4b6

test:
  secret_key_base: f830825e5ac9b5cfd1a56fd8946f5ec8edddf5c7c7d5e2086b504815eb64f983bca4a253a0d0e8e06bd6341acb6f57e9dd9f2a653a2403c3da8c6a25a80cd91a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
